train:
  spectrogram: # name of the tensor on which we apply transform
    _target_: torch.nn.Sequential # to apply several transforms sequentially
    _args_:
      - _target_: torchaudio.transforms.FrequencyMasking
        freq_mask_param: 30
      - _target_: torchaudio.transforms.TimeMasking
        time_mask_param: 80
# inference:
#   data_object: # name of the tensor on which we apply transform
#     _target_: torch.nn.Sequential # to apply several transforms sequentially
#     _args_:
#       - _target_: src.transforms.Normalize1D
#         mean: 0.5
#         std: 0.5
