train:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000
  audio_transforms:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: src.transforms.wav_augs.AddNoiseTransform  # сначала шум
        snr: 20
      - _target_: src.transforms.wav_augs.Gain     # потом усиление
        min_gain_in_db: -15.0
        max_gain_in_db: 5.0
        p: 0.5
  spectrogram:
    _target_: torchvision.transforms.v2.Compose
    transforms:
      - _target_: torchaudio.transforms.TimeMasking
        time_mask_param: 80

inference:
  get_spectrogram:
    _target_: torchaudio.transforms.MelSpectrogram
    sample_rate: 16000